import re
import json


class CodeExtractor:
    """Extract executable code from LLM text responses."""

    @classmethod
    def extract(cls, llm_response: str) -> str | None:
        """Try each extractor in order and return the first match.

        Args:
            llm_response: Raw text generated by the LLM.

        Returns:
            Extracted code string, or None if no format matched.
        """
        extractors = [
            cls._extract_python_block,
            cls._extract_xml_tool_call,
            cls._extract_json_tool_call,
            cls._extract_react_format,
        ]
        for extractor in extractors:
            result = extractor(llm_response)
            if result:
                return result
        return None

    @staticmethod
    def _extract_python_block(text: str) -> str | None:
        """Extract code from a fenced ```python ... ``` block.

        The closing fence is optional: some models stop right after the
        code (e.g. cut by a stop sequence) and never emit a trailing
        ```. In that case the block is taken up to the end of the text.
        When several blocks are present, only the first is returned.

        Args:
            text: Raw LLM output text.

        Returns:
            Code content, or None if no block was found.
        """
        pattern = r"```python\n(.*?)(?:```|\Z)"
        res = re.search(pattern, text, re.DOTALL)
        if res:
            return res.group(1).strip()
        return None

    @staticmethod
    def _extract_xml_tool_call(text: str) -> str | None:
        """Extract a tool call from XML-style <invoke> tags.

        Args:
            text: Raw LLM output text.

        Returns:
            A Python call expression, or None if no match.
        """
        res = re.search(
            r'<invoke name="(\w+)">(.*?)</invoke>', text, re.DOTALL
        )
        if not res:
            return None
        func_name = res.group(1)
        inner = res.group(2)
        params = re.findall(
            r'<parameter name="(\w+)">(.*?)</parameter>', inner, re.DOTALL
        )
        args = ", ".join(
            f"{name}={CodeExtractor._format_value(value)}"
            for name, value in params
        )
        return f"result = {func_name}({args})"

    @staticmethod
    def _extract_json_tool_call(text: str) -> str | None:
        """Extract a tool call from a <tool_call> JSON block.

        Args:
            text: Raw LLM output text.

        Returns:
            A Python call expression, or None if no match.
        """
        res = re.search(r"<tool_call>(.*?)</tool_call>", text, re.DOTALL)
        if not res:
            return None
        try:
            data = json.loads(res.group(1).strip())
        except json.JSONDecodeError:
            return None
        func_name = data["name"]
        arguments = data["arguments"]
        args = ", ".join(
            f"{k}={CodeExtractor._format_value(str(v))}"
            for k, v in arguments.items()
        )
        return f"result = {func_name}({args})"

    @staticmethod
    def _extract_react_format(text: str) -> str | None:
        """Extract a tool call from ReAct-style Action/Action Input lines.

        Args:
            text: Raw LLM output text.

        Returns:
            A Python call expression, or None if no match.
        """
        action_res = re.search(r"Action:\s*(\w+)", text)
        input_res = re.search(r"Action Input:\s*(\{.*?\})", text, re.DOTALL)
        if not action_res or not input_res:
            return None
        func_name = action_res.group(1)
        try:
            arguments = json.loads(input_res.group(1))
        except json.JSONDecodeError:
            return None
        args = ", ".join(
            f"{k}={CodeExtractor._format_value(str(v))}"
            for k, v in arguments.items()
        )

        return f"result = {func_name}({args})"

    @staticmethod
    def _format_value(value: str) -> str:
        """Format a string value as a Python literal.

        Returns the value unquoted if it is an integer or float,
        otherwise wraps it in double quotes.

        Args:
            value: String representation of the value.

        Returns:
            A Python-literal-formatted string.
        """
        value = value.strip()
        if value.lstrip("-").isdigit():
            return value
        try:
            float(value)
            return value
        except ValueError:
            return f'"{value}"'
